table_details = {
    "ISPT": {
        "LOCA_ID": {
            "Suggested Unit / Type": None,
            "type": "ID",
            "Description": "Location identifier",
            "Example": "327-16A",
        },
        "ISPT_TOP": {
            "Suggested Unit / Type": "m",
            "type": "2DP",
            "Description": "Depth to top of test",
            "Example": "13.5",
        },
        "ISPT_SEAT": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number of blows for seating drive",
            "Example": "14",
        },
        "ISPT_MAIN": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number of blows for main test drive",
            "Example": "35",
        },
        "ISPT_NPEN": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Total penetration for seating drive and test drive",
            "Example": "450",
        },
        "ISPT_NVAL": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "SPT 'N' value",
            "Example": "35",
        },
        "ISPT_REP": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "SPT reported result",
            "Example": "6,8/8,9,9,9 N=35",
        },
        "ISPT_CAS": {
            "Suggested Unit / Type": "m",
            "type": "2DP",
            "Description": "Casing depth at time of test",
            "Example": "12",
        },
        "ISPT_WAT": {
            "Suggested Unit / Type": "m",
            "type": "XN",
            "Description": "Depth to water at time of test",
            "Example": "2.50 or Dry",
        },
        "ISPT_TYPE": {
            "Suggested Unit / Type": None,
            "type": "PA",
            "Description": "Type of SPT test",
            "Example": "S",
        },
        "ISPT_HAM": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Hammer      serial      number      from manufacturer",
            "Example": "AB1234",
        },
        "ISPT_ERAT": {
            "Suggested Unit / Type": "%",
            "type": "0DP",
            "Description": "Energy ratio of the hammer",
            "Example": "60",
        },
        "ISPT_SWP": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Self-weight penetration",
            "Example": "25",
        },
        "ISPT_INC1": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number  of  blows  for  1st  Increment (Seating)",
            "Example": "6",
        },
        "ISPT_INC2": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number  of  blows  for  2nd  Increment (Seating)",
            "Example": "8",
        },
        "ISPT_INC3": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number  of  blows  for  1st  Increment (Test)",
            "Example": "8",
        },
        "ISPT_INC4": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number  of  blows  for  2nd  Increment (Test)",
            "Example": "9",
        },
        "ISPT_INC5": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number  of  blows  for  3rd  Increment (Test)",
            "Example": "9",
        },
        "ISPT_INC6": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "Number  of  blows  for  4th  Increment (Test)",
            "Example": "9",
        },
        "ISPT_PEN1": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Penetration     for     1st     Increment (Seating Drive)",
            "Example": "75",
        },
        "ISPT_PEN2": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Penetration     for     2nd     Increment (Seating Drive)",
            "Example": "75",
        },
        "ISPT_PEN3": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Penetration for 1st Increment (Test)",
            "Example": "75",
        },
        "ISPT_PEN4": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Penetration for 2nd Increment (Test)",
            "Example": "75",
        },
        "ISPT_PEN5": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Penetration for 3rd Increment (Test)",
            "Example": "75",
        },
        "ISPT_PEN6": {
            "Suggested Unit / Type": "mm",
            "type": "0DP",
            "Description": "Penetration for 4th Increment (Test)",
            "Example": "75",
        },
        "ISPT_ROCK": {
            "Suggested Unit / Type": None,
            "type": "YN",
            "Description": "SPT carried out in soft rock",
            "Example": "N",
        },
        "ISPT_REM": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Remarks",
            "Example": "Borehole topped up with water prior to test",
        },
        "ISPT_ENV": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Details of weather and environmental conditions during test",
            "Example": "Raining",
        },
        "ISPT_METH": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Test method",
            "Example": "BS EN ISO 22476-3 : 2005",
        },
        "ISPT_CRED": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Accrediting    body    and    reference number (when appropriate)",
            "Example": "UKAS 0000",
        },
        "TEST_STAT": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Test status",
            "Example": "Checked",
        },
        "FILE_FSET": {
            "Suggested Unit / Type": None,
            "type": "X",
            "Description": "Associated  file  reference  (e.g.  test result sheets)",
            "Example": "FS11",
        },
        "ISPT_N60": {
            "Suggested Unit / Type": None,
            "type": "0DP",
            "Description": "SPT  'N'  value  (corrected  by  energy ratio ISPT_ERAT)",
            "Example": "35",
        },
    }
}
